/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userGui.root_component;

import graph_utils.Angkot_rute_graph;
import userGui.component.ViewRuteTerpendek;
import userGui.component.lihatRute;

import java.awt.*;

/**
 *
 * @author ASUS
 */
public class ViewRootFrame extends javax.swing.JFrame {

    /** 
     * Creates new form ViewRootFrame
     */
    CardLayout cardLayout1, cardLayout2;
    Angkot_rute_graph angkotRuteGraph;

    public ViewRootFrame() {
        initComponents();
        cardLayout1 = (CardLayout) j_main_root_panel.getLayout();
        this.setResizable(false);
        this.setTitle("My Angkot");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_panel_utama = new javax.swing.JPanel();
        j_panel_controller = new javax.swing.JPanel();
        j_label_menu = new javax.swing.JLabel();
        b_lihat_rute = new javax.swing.JButton();
        b_rute_terpendek = new javax.swing.JButton();
        j_main_root_panel = new javax.swing.JPanel();
        j_dashboard_panel = new javax.swing.JPanel();
        l_gambar_angkot = new javax.swing.JLabel();
        p_judul_dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        j_lihat_rute_panel = new javax.swing.JPanel();
        p_lihat_judul_rute = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l_gambar_peta_angkot = new javax.swing.JLabel();
        j_rute_terpendek_panel = new javax.swing.JPanel();
        p_judul_rute_terpendek = new javax.swing.JPanel();
        l_rute_terpendek = new javax.swing.JLabel();
        p_pencari_rute_pendek_ = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_panel_controller.setBackground(new java.awt.Color(51, 153, 255));
        j_panel_controller.setForeground(new java.awt.Color(255, 102, 102));

        j_label_menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        j_label_menu.setForeground(new java.awt.Color(0, 0, 0));
        j_label_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_label_menu.setText("Menu\n");
        j_label_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_label_menuMouseClicked(evt);
            }
        });

        b_lihat_rute.setBackground(new java.awt.Color(255, 255, 255));
        b_lihat_rute.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_lihat_rute.setForeground(new java.awt.Color(0, 0, 0));
        b_lihat_rute.setText("Lihat Rute");
        b_lihat_rute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lihat_ruteActionPerformed(evt);
            }
        });

        b_rute_terpendek.setBackground(new java.awt.Color(255, 255, 255));
        b_rute_terpendek.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_rute_terpendek.setForeground(new java.awt.Color(0, 0, 0));
        b_rute_terpendek.setText("Cari Rute Terpendek");
        b_rute_terpendek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rute_terpendekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j_panel_controllerLayout = new javax.swing.GroupLayout(j_panel_controller);
        j_panel_controller.setLayout(j_panel_controllerLayout);
        j_panel_controllerLayout.setHorizontalGroup(
            j_panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_controllerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(j_panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_lihat_rute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j_label_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_rute_terpendek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        j_panel_controllerLayout.setVerticalGroup(
            j_panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_controllerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(j_label_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(b_lihat_rute, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        j_main_root_panel.setLayout(new java.awt.CardLayout());

        l_gambar_angkot.setPreferredSize(new java.awt.Dimension(450, 350));

        p_judul_dashboard.setBackground(new java.awt.Color(51, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selamat Datang di Angkotku!!!");

        javax.swing.GroupLayout p_judul_dashboardLayout = new javax.swing.GroupLayout(p_judul_dashboard);
        p_judul_dashboard.setLayout(p_judul_dashboardLayout);
        p_judul_dashboardLayout.setHorizontalGroup(
            p_judul_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_judul_dashboardLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        p_judul_dashboardLayout.setVerticalGroup(
            p_judul_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout j_dashboard_panelLayout = new javax.swing.GroupLayout(j_dashboard_panel);
        j_dashboard_panel.setLayout(j_dashboard_panelLayout);
        j_dashboard_panelLayout.setHorizontalGroup(
            j_dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_dashboard_panelLayout.createSequentialGroup()
                .addComponent(p_judul_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(j_dashboard_panelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(l_gambar_angkot, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j_dashboard_panelLayout.setVerticalGroup(
            j_dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_dashboard_panelLayout.createSequentialGroup()
                .addComponent(p_judul_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(l_gambar_angkot, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        j_main_root_panel.add(j_dashboard_panel, "card1");

        p_lihat_judul_rute.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peta Rute angkot Gunungkidul");

        javax.swing.GroupLayout p_lihat_judul_ruteLayout = new javax.swing.GroupLayout(p_lihat_judul_rute);
        p_lihat_judul_rute.setLayout(p_lihat_judul_ruteLayout);
        p_lihat_judul_ruteLayout.setHorizontalGroup(
            p_lihat_judul_ruteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_lihat_judul_ruteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        p_lihat_judul_ruteLayout.setVerticalGroup(
            p_lihat_judul_ruteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_lihat_judul_ruteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        l_gambar_peta_angkot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/peta_rute.jpeg"))); // NOI18N
        l_gambar_peta_angkot.setPreferredSize(new java.awt.Dimension(723, 434));

        javax.swing.GroupLayout j_lihat_rute_panelLayout = new javax.swing.GroupLayout(j_lihat_rute_panel);
        j_lihat_rute_panel.setLayout(j_lihat_rute_panelLayout);
        j_lihat_rute_panelLayout.setHorizontalGroup(
            j_lihat_rute_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_lihat_judul_rute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_lihat_rute_panelLayout.createSequentialGroup()
                .addComponent(l_gambar_peta_angkot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        j_lihat_rute_panelLayout.setVerticalGroup(
            j_lihat_rute_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_lihat_rute_panelLayout.createSequentialGroup()
                .addComponent(p_lihat_judul_rute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_gambar_peta_angkot, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        j_main_root_panel.add(j_lihat_rute_panel, "card2");

        p_judul_rute_terpendek.setBackground(new java.awt.Color(51, 153, 255));
        p_judul_rute_terpendek.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        l_rute_terpendek.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l_rute_terpendek.setForeground(new java.awt.Color(0, 0, 0));
        l_rute_terpendek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_rute_terpendek.setText("Rute Pendek ");

        javax.swing.GroupLayout p_judul_rute_terpendekLayout = new javax.swing.GroupLayout(p_judul_rute_terpendek);
        p_judul_rute_terpendek.setLayout(p_judul_rute_terpendekLayout);
        p_judul_rute_terpendekLayout.setHorizontalGroup(
            p_judul_rute_terpendekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_judul_rute_terpendekLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        p_judul_rute_terpendekLayout.setVerticalGroup(
            p_judul_rute_terpendekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_judul_rute_terpendekLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(l_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("Terminal sekarang");

        jLabel3.setText("jLabel3");

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jLabel5.setText("jLabel5");

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout p_pencari_rute_pendek_Layout = new javax.swing.GroupLayout(p_pencari_rute_pendek_);
        p_pencari_rute_pendek_.setLayout(p_pencari_rute_pendek_Layout);
        p_pencari_rute_pendek_Layout.setHorizontalGroup(
            p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_pencari_rute_pendek_Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        p_pencari_rute_pendek_Layout.setVerticalGroup(
            p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout j_rute_terpendek_panelLayout = new javax.swing.GroupLayout(j_rute_terpendek_panel);
        j_rute_terpendek_panel.setLayout(j_rute_terpendek_panelLayout);
        j_rute_terpendek_panelLayout.setHorizontalGroup(
            j_rute_terpendek_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_rute_terpendek_panelLayout.createSequentialGroup()
                .addComponent(p_judul_rute_terpendek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_rute_terpendek_panelLayout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(p_pencari_rute_pendek_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        j_rute_terpendek_panelLayout.setVerticalGroup(
            j_rute_terpendek_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_rute_terpendek_panelLayout.createSequentialGroup()
                .addComponent(p_judul_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_pencari_rute_pendek_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        j_main_root_panel.add(j_rute_terpendek_panel, "card3");

        javax.swing.GroupLayout j_panel_utamaLayout = new javax.swing.GroupLayout(j_panel_utama);
        j_panel_utama.setLayout(j_panel_utamaLayout);
        j_panel_utamaLayout.setHorizontalGroup(
            j_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_utamaLayout.createSequentialGroup()
                .addComponent(j_panel_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j_main_root_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j_panel_utamaLayout.setVerticalGroup(
            j_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_controller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(j_main_root_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_lihat_ruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lihat_ruteActionPerformed
        // TODO add your handling code here:
        cardLayout1.show(j_main_root_panel, "card2");
        
    }//GEN-LAST:event_b_lihat_ruteActionPerformed

    private void b_rute_terpendekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rute_terpendekActionPerformed
        // TODO add your handling code here:

        cardLayout1.show(j_main_root_panel, "card3");

    }//GEN-LAST:event_b_rute_terpendekActionPerformed

    private void j_label_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_label_menuMouseClicked
        // TODO add your handling code here:
        cardLayout1.show(j_main_root_panel, "card1");
    }//GEN-LAST:event_j_label_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRootFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_lihat_rute;
    private javax.swing.JButton b_rute_terpendek;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel j_dashboard_panel;
    private javax.swing.JLabel j_label_menu;
    private javax.swing.JPanel j_lihat_rute_panel;
    private javax.swing.JPanel j_main_root_panel;
    private javax.swing.JPanel j_panel_controller;
    private javax.swing.JPanel j_panel_utama;
    private javax.swing.JPanel j_rute_terpendek_panel;
    private javax.swing.JLabel l_gambar_angkot;
    private javax.swing.JLabel l_gambar_peta_angkot;
    private javax.swing.JLabel l_rute_terpendek;
    private javax.swing.JPanel p_judul_dashboard;
    private javax.swing.JPanel p_judul_rute_terpendek;
    private javax.swing.JPanel p_lihat_judul_rute;
    private javax.swing.JPanel p_pencari_rute_pendek_;
    // End of variables declaration//GEN-END:variables
}
