/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userGui.root_component;

import graph_utils.Angkot_rute_graph;
import userGui.component.ViewRuteTerpendek;
import userGui.component.lihatRute;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author ASUS
 */
public class ViewRootFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewRootFrame
     */
    CardLayout cardLayout1, cardLayout2;
    Angkot_rute_graph graph = new Angkot_rute_graph(20);

    public ViewRootFrame() {
        initComponents();
        cardLayout1 = (CardLayout) j_main_root_panel.getLayout();
        this.setResizable(false);
        this.setTitle("My Angkot");
        initializeGraph();

    }

    private void initializeGraph() {
        // Add graph edges here, similar to the main method in the console version
        graph.addEdge("Patuk", "Ngawen", 2);
        graph.addEdge("Patuk", "Wonosari", 6);
        graph.addEdge("Ngawen", "Wonosari", 4);
        graph.addEdge("Ngawen", "Karangmojo", 2);
        graph.addEdge("Ngawen", "Semin", 7);
        graph.addEdge("Wonosari", "Semin", 8);
        graph.addEdge("Wonosari", "Sambirejo", 4);
        graph.addEdge("Wonosari", "UGM Kampus Geologi", 10);
        graph.addEdge("Karangmojo", "Cawas", 7);
        graph.addEdge("Karangmojo", "Semin", 1);
        graph.addEdge("Sambirejo", "Semin", 4);
        graph.addEdge("Sambirejo", "Bayat", 7);
        graph.addEdge("Sambirejo", "Gereja Kelor", 6);
        graph.addEdge("Sambirejo", "Masjid Ngawen", 3);
        graph.addEdge("Semin", "Cawas", 3);
        graph.addEdge("Semin", "Bayat", 2);
        graph.addEdge("Cawas", "Bayat", 2);
        graph.addEdge("Cawas", "Nologaten", 5);
        graph.addEdge("Cawas", "RS Panti Rahayu", 6);
        graph.addEdge("Bayat", "RS Panti Rahayu", 3);
        graph.addEdge("Bayat", "Gereja Kelor", 3);
        graph.addEdge("Gereja Kelor", "RS Panti Rahayu", 1);
        graph.addEdge("Gereja Kelor", "Vihara Candirejo", 1);
        graph.addEdge("Gereja Kelor", "Masjid Ngawen", 2);
        graph.addEdge("Masjid Ngawen", "Vihara Candirejo", 4);
        graph.addEdge("Masjid Ngawen", "UGM Kampus Geologi", 3);
        graph.addEdge("RS Panti Rahayu", "Vihara Candirejo", 3);
        graph.addEdge("RS Panti Rahayu", "Nologaten", 2);
        graph.addEdge("RS Panti Rahayu", "Candirejo", 3);
        graph.addEdge("Nologaten", "Candirejo", 5);
        graph.addEdge("Candirejo", "Pasar Sambeng", 6);
        graph.addEdge("Candirejo", "Vihara Candirejo", 3);
        graph.addEdge("UGM Kampus Geologi", "Pasar Sambeng", 3);
        graph.addEdge("Vihara Candirejo", "Pasar Sambeng", 4);
        System.out.println("Graph berhasil dibuat !! ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_panel_utama = new javax.swing.JPanel();
        j_panel_controller = new javax.swing.JPanel();
        j_label_menu = new javax.swing.JLabel();
        b_lihat_rute = new javax.swing.JButton();
        b_rute_terpendek = new javax.swing.JButton();
        j_main_root_panel = new javax.swing.JPanel();
        j_dashboard_panel = new javax.swing.JPanel();
        l_gambar_angkot = new javax.swing.JLabel();
        p_judul_dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        j_lihat_rute_panel = new javax.swing.JPanel();
        p_lihat_judul_rute = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l_gambar_peta_angkot = new javax.swing.JLabel();
        j_rute_terpendek_panel = new javax.swing.JPanel();
        p_judul_rute_terpendek = new javax.swing.JPanel();
        l_rute_terpendek = new javax.swing.JLabel();
        p_pencari_rute_pendek_ = new javax.swing.JPanel();
        l_terminal_awal = new javax.swing.JLabel();
        l_terminal_tujuan = new javax.swing.JLabel();
        t_terminal_awal = new javax.swing.JTextField();
        t_terminal_tujuan = new javax.swing.JTextField();
        l_rute_terpendek_info = new javax.swing.JLabel();
        t_rute_terpendek = new javax.swing.JTextField();
        b_mulai_rute = new javax.swing.JButton();
        b_reset_input = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_panel_controller.setBackground(new java.awt.Color(51, 153, 255));
        j_panel_controller.setForeground(new java.awt.Color(255, 102, 102));

        j_label_menu.setBackground(new java.awt.Color(255, 255, 255));
        j_label_menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        j_label_menu.setForeground(new java.awt.Color(0, 0, 0));
        j_label_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_label_menu.setText("Menu\n");
        j_label_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_label_menuMouseClicked(evt);
            }
        });

        b_lihat_rute.setBackground(new java.awt.Color(255, 255, 255));
        b_lihat_rute.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_lihat_rute.setForeground(new java.awt.Color(0, 0, 0));
        b_lihat_rute.setText("Lihat Rute");
        b_lihat_rute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lihat_ruteActionPerformed(evt);
            }
        });

        b_rute_terpendek.setBackground(new java.awt.Color(255, 255, 255));
        b_rute_terpendek.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_rute_terpendek.setForeground(new java.awt.Color(0, 0, 0));
        b_rute_terpendek.setText("Cari Rute Terpendek");
        b_rute_terpendek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rute_terpendekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j_panel_controllerLayout = new javax.swing.GroupLayout(j_panel_controller);
        j_panel_controller.setLayout(j_panel_controllerLayout);
        j_panel_controllerLayout.setHorizontalGroup(
            j_panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_controllerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(j_panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_lihat_rute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j_label_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_rute_terpendek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        j_panel_controllerLayout.setVerticalGroup(
            j_panel_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_controllerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(j_label_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(b_lihat_rute, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        j_main_root_panel.setLayout(new java.awt.CardLayout());

        l_gambar_angkot.setPreferredSize(new java.awt.Dimension(450, 350));

        p_judul_dashboard.setBackground(new java.awt.Color(51, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selamat Datang di Angkotku!!!");

        javax.swing.GroupLayout p_judul_dashboardLayout = new javax.swing.GroupLayout(p_judul_dashboard);
        p_judul_dashboard.setLayout(p_judul_dashboardLayout);
        p_judul_dashboardLayout.setHorizontalGroup(
            p_judul_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_judul_dashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        p_judul_dashboardLayout.setVerticalGroup(
            p_judul_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout j_dashboard_panelLayout = new javax.swing.GroupLayout(j_dashboard_panel);
        j_dashboard_panel.setLayout(j_dashboard_panelLayout);
        j_dashboard_panelLayout.setHorizontalGroup(
            j_dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_dashboard_panelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(l_gambar_angkot, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
            .addComponent(p_judul_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        j_dashboard_panelLayout.setVerticalGroup(
            j_dashboard_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_dashboard_panelLayout.createSequentialGroup()
                .addComponent(p_judul_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(l_gambar_angkot, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        j_main_root_panel.add(j_dashboard_panel, "card1");

        p_lihat_judul_rute.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peta Rute angkot Gunungkidul");

        javax.swing.GroupLayout p_lihat_judul_ruteLayout = new javax.swing.GroupLayout(p_lihat_judul_rute);
        p_lihat_judul_rute.setLayout(p_lihat_judul_ruteLayout);
        p_lihat_judul_ruteLayout.setHorizontalGroup(
            p_lihat_judul_ruteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_lihat_judul_ruteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        p_lihat_judul_ruteLayout.setVerticalGroup(
            p_lihat_judul_ruteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_lihat_judul_ruteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        l_gambar_peta_angkot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/peta_rute.jpeg"))); // NOI18N

        javax.swing.GroupLayout j_lihat_rute_panelLayout = new javax.swing.GroupLayout(j_lihat_rute_panel);
        j_lihat_rute_panel.setLayout(j_lihat_rute_panelLayout);
        j_lihat_rute_panelLayout.setHorizontalGroup(
            j_lihat_rute_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_lihat_judul_rute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_lihat_rute_panelLayout.createSequentialGroup()
                .addComponent(l_gambar_peta_angkot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        j_lihat_rute_panelLayout.setVerticalGroup(
            j_lihat_rute_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_lihat_rute_panelLayout.createSequentialGroup()
                .addComponent(p_lihat_judul_rute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_gambar_peta_angkot, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        j_main_root_panel.add(j_lihat_rute_panel, "card2");

        p_judul_rute_terpendek.setBackground(new java.awt.Color(51, 153, 255));
        p_judul_rute_terpendek.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        l_rute_terpendek.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        l_rute_terpendek.setForeground(new java.awt.Color(0, 0, 0));
        l_rute_terpendek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_rute_terpendek.setText("Rute Pendek ");

        javax.swing.GroupLayout p_judul_rute_terpendekLayout = new javax.swing.GroupLayout(p_judul_rute_terpendek);
        p_judul_rute_terpendek.setLayout(p_judul_rute_terpendekLayout);
        p_judul_rute_terpendekLayout.setHorizontalGroup(
            p_judul_rute_terpendekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_judul_rute_terpendekLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(l_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        p_judul_rute_terpendekLayout.setVerticalGroup(
            p_judul_rute_terpendekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_judul_rute_terpendekLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(l_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        l_terminal_awal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_terminal_awal.setText("Terminal sekarang");

        l_terminal_tujuan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_terminal_tujuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_terminal_tujuan.setText("Terminal Tujuan");

        t_terminal_awal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        t_terminal_tujuan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        l_rute_terpendek_info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l_rute_terpendek_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_rute_terpendek_info.setText("Rute Terpendek");

        t_rute_terpendek.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        b_mulai_rute.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_mulai_rute.setText("Mulai Rute");
        b_mulai_rute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_mulai_ruteActionPerformed(evt);
            }
        });

        b_reset_input.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_reset_input.setText("Reset");
        b_reset_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_reset_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_pencari_rute_pendek_Layout = new javax.swing.GroupLayout(p_pencari_rute_pendek_);
        p_pencari_rute_pendek_.setLayout(p_pencari_rute_pendek_Layout);
        p_pencari_rute_pendek_Layout.setHorizontalGroup(
            p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(b_mulai_rute, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_reset_input, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l_rute_terpendek_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_terminal_tujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_terminal_awal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(t_terminal_tujuan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                .addComponent(t_terminal_awal, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        p_pencari_rute_pendek_Layout.setVerticalGroup(
            p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pencari_rute_pendek_Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_terminal_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_terminal_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_terminal_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_terminal_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_rute_terpendek_info, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(p_pencari_rute_pendek_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_mulai_rute, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_reset_input, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout j_rute_terpendek_panelLayout = new javax.swing.GroupLayout(j_rute_terpendek_panel);
        j_rute_terpendek_panel.setLayout(j_rute_terpendek_panelLayout);
        j_rute_terpendek_panelLayout.setHorizontalGroup(
            j_rute_terpendek_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_rute_terpendek_panelLayout.createSequentialGroup()
                .addComponent(p_judul_rute_terpendek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_rute_terpendek_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p_pencari_rute_pendek_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        j_rute_terpendek_panelLayout.setVerticalGroup(
            j_rute_terpendek_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_rute_terpendek_panelLayout.createSequentialGroup()
                .addComponent(p_judul_rute_terpendek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_pencari_rute_pendek_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        j_main_root_panel.add(j_rute_terpendek_panel, "card3");

        javax.swing.GroupLayout j_panel_utamaLayout = new javax.swing.GroupLayout(j_panel_utama);
        j_panel_utama.setLayout(j_panel_utamaLayout);
        j_panel_utamaLayout.setHorizontalGroup(
            j_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_utamaLayout.createSequentialGroup()
                .addComponent(j_panel_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j_main_root_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j_panel_utamaLayout.setVerticalGroup(
            j_panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_controller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(j_main_root_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_lihat_ruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lihat_ruteActionPerformed
        // TODO add your handling code here:
        cardLayout1.show(j_main_root_panel, "card2");

    }//GEN-LAST:event_b_lihat_ruteActionPerformed

    private void b_rute_terpendekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rute_terpendekActionPerformed
        // TODO add your handling code here:
        cardLayout1.show(j_main_root_panel, "card3");

    }//GEN-LAST:event_b_rute_terpendekActionPerformed

    private void j_label_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_label_menuMouseClicked
        // TODO add your handling code here:
        cardLayout1.show(j_main_root_panel, "card1");
    }//GEN-LAST:event_j_label_menuMouseClicked

    private void b_mulai_ruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_mulai_ruteActionPerformed
        // TODO add your handling code here:
        try {
            String awal = t_terminal_awal.getText();
            String akhir = t_terminal_tujuan.getText();
            List<String> shortestPath = graph.findShortestPath(awal, akhir);

            if (shortestPath != null) {
                t_rute_terpendek.setText(String.join(" -> ", shortestPath));
            }

        } catch (ArrayIndexOutOfBoundsException exception) {
            JOptionPane.showMessageDialog(null, "Vertex Invalid");
        }

    }//GEN-LAST:event_b_mulai_ruteActionPerformed

    private void b_reset_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_reset_inputActionPerformed
        // TODO add your handling code here:
        t_terminal_awal.setText("");
        t_terminal_tujuan.setText("");
        t_rute_terpendek.setText("");
    }//GEN-LAST:event_b_reset_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException
                | InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRootFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRootFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_lihat_rute;
    private javax.swing.JButton b_mulai_rute;
    private javax.swing.JButton b_reset_input;
    private javax.swing.JButton b_rute_terpendek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel j_dashboard_panel;
    private javax.swing.JLabel j_label_menu;
    private javax.swing.JPanel j_lihat_rute_panel;
    private javax.swing.JPanel j_main_root_panel;
    private javax.swing.JPanel j_panel_controller;
    private javax.swing.JPanel j_panel_utama;
    private javax.swing.JPanel j_rute_terpendek_panel;
    private javax.swing.JLabel l_gambar_angkot;
    private javax.swing.JLabel l_gambar_peta_angkot;
    private javax.swing.JLabel l_rute_terpendek;
    private javax.swing.JLabel l_rute_terpendek_info;
    private javax.swing.JLabel l_terminal_awal;
    private javax.swing.JLabel l_terminal_tujuan;
    private javax.swing.JPanel p_judul_dashboard;
    private javax.swing.JPanel p_judul_rute_terpendek;
    private javax.swing.JPanel p_lihat_judul_rute;
    private javax.swing.JPanel p_pencari_rute_pendek_;
    private javax.swing.JTextField t_rute_terpendek;
    private javax.swing.JTextField t_terminal_awal;
    private javax.swing.JTextField t_terminal_tujuan;
    // End of variables declaration//GEN-END:variables
}
